### ISSUE TITLE
Adding Security Schemes to OpenAPI Documentation

### ISSUE THREAD

**Issue by jsudiaman** [kennethreitz/responder#259]
https://swagger.io/docs/specification/authentication/basic-authentication/

Using OpenAPI, in order to document a route that requires authentication (i.e. Basic Auth in this case), we need the following entry in `schema.yml`:

```YAML
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic

...

paths:
  /something:
    get:
      security:
        - basicAuth:[]
```

However, I couldn't find a way to add the `components/securitySchemes` entry using Responder. Is there currently a way to do it?
